services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - REDIS_HOST=redis
    restart: always
    ports:
      - 127.0.0.1:8080:80
    logging:
      options:
        max-size: "64m"

  redis:
    image: docker.arvancloud.ir/redis:alpine
    restart: always
    # ports:
    #   - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
